name: ci

on:
  push:
    branches:
      - main
      - renovate/*
      - dev/*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - dev/*
      - stable/*

jobs:
  ci:
    uses: AmpelProject/Ampel-interface/.github/workflows/ci.yml@964c65fc510c7f2e1cc8f279185128acd249928c # ci-py12-v8
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    with:
      mongo: true
      # renovate: datasource=python-version depName=python versioning=python
      python-version: "3.13"
      # renovate: datasource=pypi depName=poetry versioning=pep440
      poetry-version: "1.8.5"
      # renovate: datasource=pypi depName=ruff versioning=pep440
      ruff-version: "0.9.4"
      lint: true
      format: true
